name: publish-action
on:
  release:
    types: released
concurrency: ${{ github.workflow }}
jobs:
  get-cargo-package-name:
    permissions:
      contents: write
    outputs:
      cargo-package-name: ${{ steps.get-cargo-package-name.outputs.cargo-package-name }}
    runs-on: ubuntu-latest
    steps:
      - id: get-cargo-package-name
        run: |
          name=$(echo "$TAG" | sed 's/-v[0-9]\+\.[0-9]\+\.[0-9]\+$//')
          echo "cargo-package-name=$name" >> "$GITHUB_OUTPUT"
        env:
          TAG: ${{ github.event.release.tag_name }}
  cargo-publish:
    needs: get-cargo-package-name
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo publish --package "$PACKAGE"
        env:
          PACKAGE: ${{ needs.get-cargo-package-name.outputs.cargo-package-name }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
