name: cargo test
on:
  push:
    branches: "main"
    paths-ignore:
      - "**/README.md"
      - "**/.gitignore"
      - "**/LICENSE-APACHE"
      - "**/LICENSE-MIT"
      - .github/**
      - "!.github/workflows/cargo-test.yml"
  pull_request:
    paths-ignore:
      - "**/README.md"
      - "**/.gitignore"
      - "**/LICENSE-APACHE"
      - "**/LICENSE-MIT"
      - .github/**
      - "!.github/workflows/cargo-test.yml"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  get-changed-cargo-packages:
    runs-on: ubuntu-latest
    outputs:
      changed-cargo-packages: ${{ steps.get-changed-cargo-packages.outputs.changed-cargo-packages }}
    steps:
      - uses: actions/checkout@v4
      - id: get-changed-cargo-packages
        uses: jcbhmr/get-changed-cargo-packages@v1
  cargo-test:
    needs: get-changed-cargo-packages
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        package: ${{ fromJSON(needs.get-changed-packages.outputs.changed-packages) }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: cargo test --package "$PACKAGE" --all-features
        env:
          PACKAGE: ${{ matrix.package }}
