name: feature-matrix

on:
  workflow_call:
    outputs:
      matrix:
        description: "the feature matrix"
        value: ${{ jobs.matrix.outputs.matrix }}

jobs:
  matrix:
    name: Generate feature matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.compute-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable

      - name: Compute feature matrix
        id: compute-matrix
        run: |
          cargo install cargo-feature-combinations
          echo "matrix=$(cargo feature-combinations matrix)" >> $GITHUB_OUTPUT
